import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { supabaseAdmin } from "@/integrations/supabase/client.server";

// Get the signed-in user's stream token (auto-generated by DB default).
export const getMyStreamToken = createServerFn({ method: "GET" })
  .middleware([requireSupabaseAuth])
  .handler(async ({ context }) => {
    const { userId } = context;
    const { data, error } = await supabaseAdmin
      .from("profiles")
      .select("stream_token")
      .eq("id", userId)
      .maybeSingle();
    if (error) throw new Error(error.message);
    return { token: data?.stream_token as string | undefined };
  });

// Regenerate the signed-in user's stream token.
export const regenerateMyStreamToken = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .handler(async ({ context }) => {
    const { userId } = context;
    const { data, error } = await supabaseAdmin
      .from("profiles")
      .update({ stream_token: crypto.randomUUID() })
      .eq("id", userId)
      .select("stream_token")
      .single();
    if (error) throw new Error(error.message);
    return { token: data.stream_token as string };
  });

// Resolve a stream token to a user id (called by the OBS /output page; no auth).
export const resolveStreamToken = createServerFn({ method: "GET" })
  .inputValidator((input) => z.object({ token: z.string().uuid() }).parse(input))
  .handler(async ({ data }) => {
    const { data: row, error } = await supabaseAdmin
      .from("profiles")
      .select("id")
      .eq("stream_token", data.token)
      .maybeSingle();
    if (error) throw new Error(error.message);
    if (!row) throw new Error("Invalid stream token");
    return { userId: row.id as string };
  });
