/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OutputRouteImport } from './routes/output'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventorRouteImport } from './routes/inventor'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InventorIndexRouteImport } from './routes/inventor.index'
import { Route as InventorUsersRouteImport } from './routes/inventor.users'
import { Route as InventorMonitorRouteImport } from './routes/inventor.monitor'
import { Route as InventorLedgerRouteImport } from './routes/inventor.ledger'
import { Route as InventorFinanceRouteImport } from './routes/inventor.finance'
import { Route as AppStreamRouteImport } from './routes/_app.stream'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCreditsRouteImport } from './routes/_app.credits'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as ApiPublicTrackVisitRouteImport } from './routes/api/public/track-visit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OutputRoute = OutputRouteImport.update({
  id: '/output',
  path: '/output',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventorRoute = InventorRouteImport.update({
  id: '/inventor',
  path: '/inventor',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventorIndexRoute = InventorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InventorRoute,
} as any)
const InventorUsersRoute = InventorUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => InventorRoute,
} as any)
const InventorMonitorRoute = InventorMonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => InventorRoute,
} as any)
const InventorLedgerRoute = InventorLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => InventorRoute,
} as any)
const InventorFinanceRoute = InventorFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => InventorRoute,
} as any)
const AppStreamRoute = AppStreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCreditsRoute = AppCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicTrackVisitRoute = ApiPublicTrackVisitRouteImport.update({
  id: '/api/public/track-visit',
  path: '/api/public/track-visit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inventor': typeof InventorRouteWithChildren
  '/login': typeof LoginRoute
  '/output': typeof OutputRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/billing': typeof AppBillingRoute
  '/credits': typeof AppCreditsRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/stream': typeof AppStreamRoute
  '/inventor/finance': typeof InventorFinanceRoute
  '/inventor/ledger': typeof InventorLedgerRoute
  '/inventor/monitor': typeof InventorMonitorRoute
  '/inventor/users': typeof InventorUsersRoute
  '/inventor/': typeof InventorIndexRoute
  '/api/public/track-visit': typeof ApiPublicTrackVisitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/output': typeof OutputRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/billing': typeof AppBillingRoute
  '/credits': typeof AppCreditsRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/stream': typeof AppStreamRoute
  '/inventor/finance': typeof InventorFinanceRoute
  '/inventor/ledger': typeof InventorLedgerRoute
  '/inventor/monitor': typeof InventorMonitorRoute
  '/inventor/users': typeof InventorUsersRoute
  '/inventor': typeof InventorIndexRoute
  '/api/public/track-visit': typeof ApiPublicTrackVisitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inventor': typeof InventorRouteWithChildren
  '/login': typeof LoginRoute
  '/output': typeof OutputRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/credits': typeof AppCreditsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/stream': typeof AppStreamRoute
  '/inventor/finance': typeof InventorFinanceRoute
  '/inventor/ledger': typeof InventorLedgerRoute
  '/inventor/monitor': typeof InventorMonitorRoute
  '/inventor/users': typeof InventorUsersRoute
  '/inventor/': typeof InventorIndexRoute
  '/api/public/track-visit': typeof ApiPublicTrackVisitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/inventor'
    | '/login'
    | '/output'
    | '/reset-password'
    | '/signup'
    | '/billing'
    | '/credits'
    | '/dashboard'
    | '/settings'
    | '/stream'
    | '/inventor/finance'
    | '/inventor/ledger'
    | '/inventor/monitor'
    | '/inventor/users'
    | '/inventor/'
    | '/api/public/track-visit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/output'
    | '/reset-password'
    | '/signup'
    | '/billing'
    | '/credits'
    | '/dashboard'
    | '/settings'
    | '/stream'
    | '/inventor/finance'
    | '/inventor/ledger'
    | '/inventor/monitor'
    | '/inventor/users'
    | '/inventor'
    | '/api/public/track-visit'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/forgot-password'
    | '/inventor'
    | '/login'
    | '/output'
    | '/reset-password'
    | '/signup'
    | '/_app/billing'
    | '/_app/credits'
    | '/_app/dashboard'
    | '/_app/settings'
    | '/_app/stream'
    | '/inventor/finance'
    | '/inventor/ledger'
    | '/inventor/monitor'
    | '/inventor/users'
    | '/inventor/'
    | '/api/public/track-visit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InventorRoute: typeof InventorRouteWithChildren
  LoginRoute: typeof LoginRoute
  OutputRoute: typeof OutputRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiPublicTrackVisitRoute: typeof ApiPublicTrackVisitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/output': {
      id: '/output'
      path: '/output'
      fullPath: '/output'
      preLoaderRoute: typeof OutputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventor': {
      id: '/inventor'
      path: '/inventor'
      fullPath: '/inventor'
      preLoaderRoute: typeof InventorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventor/': {
      id: '/inventor/'
      path: '/'
      fullPath: '/inventor/'
      preLoaderRoute: typeof InventorIndexRouteImport
      parentRoute: typeof InventorRoute
    }
    '/inventor/users': {
      id: '/inventor/users'
      path: '/users'
      fullPath: '/inventor/users'
      preLoaderRoute: typeof InventorUsersRouteImport
      parentRoute: typeof InventorRoute
    }
    '/inventor/monitor': {
      id: '/inventor/monitor'
      path: '/monitor'
      fullPath: '/inventor/monitor'
      preLoaderRoute: typeof InventorMonitorRouteImport
      parentRoute: typeof InventorRoute
    }
    '/inventor/ledger': {
      id: '/inventor/ledger'
      path: '/ledger'
      fullPath: '/inventor/ledger'
      preLoaderRoute: typeof InventorLedgerRouteImport
      parentRoute: typeof InventorRoute
    }
    '/inventor/finance': {
      id: '/inventor/finance'
      path: '/finance'
      fullPath: '/inventor/finance'
      preLoaderRoute: typeof InventorFinanceRouteImport
      parentRoute: typeof InventorRoute
    }
    '/_app/stream': {
      id: '/_app/stream'
      path: '/stream'
      fullPath: '/stream'
      preLoaderRoute: typeof AppStreamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/credits': {
      id: '/_app/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof AppCreditsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/track-visit': {
      id: '/api/public/track-visit'
      path: '/api/public/track-visit'
      fullPath: '/api/public/track-visit'
      preLoaderRoute: typeof ApiPublicTrackVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppCreditsRoute: typeof AppCreditsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStreamRoute: typeof AppStreamRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppCreditsRoute: AppCreditsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStreamRoute: AppStreamRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface InventorRouteChildren {
  InventorFinanceRoute: typeof InventorFinanceRoute
  InventorLedgerRoute: typeof InventorLedgerRoute
  InventorMonitorRoute: typeof InventorMonitorRoute
  InventorUsersRoute: typeof InventorUsersRoute
  InventorIndexRoute: typeof InventorIndexRoute
}

const InventorRouteChildren: InventorRouteChildren = {
  InventorFinanceRoute: InventorFinanceRoute,
  InventorLedgerRoute: InventorLedgerRoute,
  InventorMonitorRoute: InventorMonitorRoute,
  InventorUsersRoute: InventorUsersRoute,
  InventorIndexRoute: InventorIndexRoute,
}

const InventorRouteWithChildren = InventorRoute._addFileChildren(
  InventorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InventorRoute: InventorRouteWithChildren,
  LoginRoute: LoginRoute,
  OutputRoute: OutputRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiPublicTrackVisitRoute: ApiPublicTrackVisitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
