/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as InventorRouteImport } from './routes/inventor'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as OutputRouteImport } from './routes/output'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AppApiKeysRouteImport } from './routes/_app.api-keys'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as AppCreditsRouteImport } from './routes/_app.credits'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppStreamRouteImport } from './routes/_app.stream'
import { Route as AppSupportRouteImport } from './routes/_app.support'
import { Route as AppTutorialRouteImport } from './routes/_app.tutorial'
import { Route as AppVoiceRouteImport } from './routes/_app.voice'
import { Route as AdminVoiceRouteImport } from './routes/admin_.voice'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as InventorIndexRouteImport } from './routes/inventor.index'
import { Route as InventorFinanceRouteImport } from './routes/inventor.finance'
import { Route as InventorHistoryRouteImport } from './routes/inventor.history'
import { Route as InventorIpSearchRouteImport } from './routes/inventor.ip-search'
import { Route as InventorLedgerRouteImport } from './routes/inventor.ledger'
import { Route as InventorMonitorRouteImport } from './routes/inventor.monitor'
import { Route as InventorPurchasesRouteImport } from './routes/inventor.purchases'
import { Route as InventorRecordingsRouteImport } from './routes/inventor.recordings'
import { Route as InventorSupportRouteImport } from './routes/inventor.support'
import { Route as InventorTutorialsRouteImport } from './routes/inventor.tutorials'
import { Route as InventorUsersRouteImport } from './routes/inventor.users'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicResolveStreamTokenRouteImport } from './routes/api/public/resolve-stream-token'
import { Route as ApiPublicTrackVisitRouteImport } from './routes/api/public/track-visit'
import { Route as ApiVoiceStreamRouteImport } from './routes/api/voice/stream'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicApiV1SplatRouteImport } from './routes/api/public/api-v1/$'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const InventorRoute = InventorRouteImport.update({
  id: '/inventor',
  path: '/inventor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OutputRoute = OutputRouteImport.update({
  id: '/output',
  path: '/output',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppApiKeysRoute = AppApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppCreditsRoute = AppCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStreamRoute = AppStreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppTutorialRoute = AppTutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => AppRoute,
} as any)
const AppVoiceRoute = AppVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => AppRoute,
} as any)
const AdminVoiceRoute = AdminVoiceRouteImport.update({
  id: '/admin_/voice',
  path: '/admin/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const InventorIndexRoute = InventorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InventorRoute,
} as any)
const InventorFinanceRoute = InventorFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => InventorRoute,
} as any)
const InventorHistoryRoute = InventorHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => InventorRoute,
} as any)
const InventorIpSearchRoute = InventorIpSearchRouteImport.update({
  id: '/ip-search',
  path: '/ip-search',
  getParentRoute: () => InventorRoute,
} as any)
const InventorLedgerRoute = InventorLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => InventorRoute,
} as any)
const InventorMonitorRoute = InventorMonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => InventorRoute,
} as any)
const InventorPurchasesRoute = InventorPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => InventorRoute,
} as any)
const InventorRecordingsRoute = InventorRecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => InventorRoute,
} as any)
const InventorSupportRoute = InventorSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => InventorRoute,
} as any)
const InventorTutorialsRoute = InventorTutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => InventorRoute,
} as any)
const InventorUsersRoute = InventorUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => InventorRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicResolveStreamTokenRoute =
  ApiPublicResolveStreamTokenRouteImport.update({
    id: '/api/public/resolve-stream-token',
    path: '/api/public/resolve-stream-token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTrackVisitRoute = ApiPublicTrackVisitRouteImport.update({
  id: '/api/public/track-visit',
  path: '/api/public/track-visit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceStreamRoute = ApiVoiceStreamRouteImport.update({
  id: '/api/voice/stream',
  path: '/api/voice/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicApiV1SplatRoute = ApiPublicApiV1SplatRouteImport.update({
  id: '/api/public/api-v1/$',
  path: '/api/public/api-v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inventor': typeof InventorRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/output': typeof OutputRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api-keys': typeof AppApiKeysRoute
  '/billing': typeof AppBillingRoute
  '/credits': typeof AppCreditsRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/stream': typeof AppStreamRoute
  '/support': typeof AppSupportRoute
  '/tutorial': typeof AppTutorialRoute
  '/voice': typeof AppVoiceRoute
  '/admin/voice': typeof AdminVoiceRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/inventor/finance': typeof InventorFinanceRoute
  '/inventor/history': typeof InventorHistoryRoute
  '/inventor/ip-search': typeof InventorIpSearchRoute
  '/inventor/ledger': typeof InventorLedgerRoute
  '/inventor/monitor': typeof InventorMonitorRoute
  '/inventor/purchases': typeof InventorPurchasesRoute
  '/inventor/recordings': typeof InventorRecordingsRoute
  '/inventor/support': typeof InventorSupportRoute
  '/inventor/tutorials': typeof InventorTutorialsRoute
  '/inventor/users': typeof InventorUsersRoute
  '/inventor/': typeof InventorIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/resolve-stream-token': typeof ApiPublicResolveStreamTokenRoute
  '/api/public/track-visit': typeof ApiPublicTrackVisitRoute
  '/api/voice/stream': typeof ApiVoiceStreamRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/api-v1/$': typeof ApiPublicApiV1SplatRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/output': typeof OutputRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api-keys': typeof AppApiKeysRoute
  '/billing': typeof AppBillingRoute
  '/credits': typeof AppCreditsRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/stream': typeof AppStreamRoute
  '/support': typeof AppSupportRoute
  '/tutorial': typeof AppTutorialRoute
  '/voice': typeof AppVoiceRoute
  '/admin/voice': typeof AdminVoiceRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/inventor/finance': typeof InventorFinanceRoute
  '/inventor/history': typeof InventorHistoryRoute
  '/inventor/ip-search': typeof InventorIpSearchRoute
  '/inventor/ledger': typeof InventorLedgerRoute
  '/inventor/monitor': typeof InventorMonitorRoute
  '/inventor/purchases': typeof InventorPurchasesRoute
  '/inventor/recordings': typeof InventorRecordingsRoute
  '/inventor/support': typeof InventorSupportRoute
  '/inventor/tutorials': typeof InventorTutorialsRoute
  '/inventor/users': typeof InventorUsersRoute
  '/inventor': typeof InventorIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/resolve-stream-token': typeof ApiPublicResolveStreamTokenRoute
  '/api/public/track-visit': typeof ApiPublicTrackVisitRoute
  '/api/voice/stream': typeof ApiVoiceStreamRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/api-v1/$': typeof ApiPublicApiV1SplatRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inventor': typeof InventorRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/output': typeof OutputRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_app/api-keys': typeof AppApiKeysRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/credits': typeof AppCreditsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/stream': typeof AppStreamRoute
  '/_app/support': typeof AppSupportRoute
  '/_app/tutorial': typeof AppTutorialRoute
  '/_app/voice': typeof AppVoiceRoute
  '/admin_/voice': typeof AdminVoiceRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/inventor/finance': typeof InventorFinanceRoute
  '/inventor/history': typeof InventorHistoryRoute
  '/inventor/ip-search': typeof InventorIpSearchRoute
  '/inventor/ledger': typeof InventorLedgerRoute
  '/inventor/monitor': typeof InventorMonitorRoute
  '/inventor/purchases': typeof InventorPurchasesRoute
  '/inventor/recordings': typeof InventorRecordingsRoute
  '/inventor/support': typeof InventorSupportRoute
  '/inventor/tutorials': typeof InventorTutorialsRoute
  '/inventor/users': typeof InventorUsersRoute
  '/inventor/': typeof InventorIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/resolve-stream-token': typeof ApiPublicResolveStreamTokenRoute
  '/api/public/track-visit': typeof ApiPublicTrackVisitRoute
  '/api/voice/stream': typeof ApiVoiceStreamRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/api-v1/$': typeof ApiPublicApiV1SplatRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/inventor'
    | '/login'
    | '/mcp'
    | '/output'
    | '/privacy'
    | '/refunds'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/trust'
    | '/unsubscribe'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api-keys'
    | '/billing'
    | '/credits'
    | '/dashboard'
    | '/settings'
    | '/stream'
    | '/support'
    | '/tutorial'
    | '/voice'
    | '/admin/voice'
    | '/email/unsubscribe'
    | '/inventor/finance'
    | '/inventor/history'
    | '/inventor/ip-search'
    | '/inventor/ledger'
    | '/inventor/monitor'
    | '/inventor/purchases'
    | '/inventor/recordings'
    | '/inventor/support'
    | '/inventor/tutorials'
    | '/inventor/users'
    | '/inventor/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/resolve-stream-token'
    | '/api/public/track-visit'
    | '/api/voice/stream'
    | '/lovable/email/suppression'
    | '/api/public/api-v1/$'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/mcp'
    | '/output'
    | '/privacy'
    | '/refunds'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/trust'
    | '/unsubscribe'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api-keys'
    | '/billing'
    | '/credits'
    | '/dashboard'
    | '/settings'
    | '/stream'
    | '/support'
    | '/tutorial'
    | '/voice'
    | '/admin/voice'
    | '/email/unsubscribe'
    | '/inventor/finance'
    | '/inventor/history'
    | '/inventor/ip-search'
    | '/inventor/ledger'
    | '/inventor/monitor'
    | '/inventor/purchases'
    | '/inventor/recordings'
    | '/inventor/support'
    | '/inventor/tutorials'
    | '/inventor/users'
    | '/inventor'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/resolve-stream-token'
    | '/api/public/track-visit'
    | '/api/voice/stream'
    | '/lovable/email/suppression'
    | '/api/public/api-v1/$'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/forgot-password'
    | '/inventor'
    | '/login'
    | '/mcp'
    | '/output'
    | '/privacy'
    | '/refunds'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/trust'
    | '/unsubscribe'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_app/api-keys'
    | '/_app/billing'
    | '/_app/credits'
    | '/_app/dashboard'
    | '/_app/settings'
    | '/_app/stream'
    | '/_app/support'
    | '/_app/tutorial'
    | '/_app/voice'
    | '/admin_/voice'
    | '/email/unsubscribe'
    | '/inventor/finance'
    | '/inventor/history'
    | '/inventor/ip-search'
    | '/inventor/ledger'
    | '/inventor/monitor'
    | '/inventor/purchases'
    | '/inventor/recordings'
    | '/inventor/support'
    | '/inventor/tutorials'
    | '/inventor/users'
    | '/inventor/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/resolve-stream-token'
    | '/api/public/track-visit'
    | '/api/voice/stream'
    | '/lovable/email/suppression'
    | '/api/public/api-v1/$'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InventorRoute: typeof InventorRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  OutputRoute: typeof OutputRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundsRoute: typeof RefundsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  TrustRoute: typeof TrustRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AdminVoiceRoute: typeof AdminVoiceRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicResolveStreamTokenRoute: typeof ApiPublicResolveStreamTokenRoute
  ApiPublicTrackVisitRoute: typeof ApiPublicTrackVisitRoute
  ApiVoiceStreamRoute: typeof ApiVoiceStreamRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicApiV1SplatRoute: typeof ApiPublicApiV1SplatRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventor': {
      id: '/inventor'
      path: '/inventor'
      fullPath: '/inventor'
      preLoaderRoute: typeof InventorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/output': {
      id: '/output'
      path: '/output'
      fullPath: '/output'
      preLoaderRoute: typeof OutputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/api-keys': {
      id: '/_app/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AppApiKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/credits': {
      id: '/_app/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof AppCreditsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stream': {
      id: '/_app/stream'
      path: '/stream'
      fullPath: '/stream'
      preLoaderRoute: typeof AppStreamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support': {
      id: '/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tutorial': {
      id: '/_app/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof AppTutorialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/voice': {
      id: '/_app/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof AppVoiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin_/voice': {
      id: '/admin_/voice'
      path: '/admin/voice'
      fullPath: '/admin/voice'
      preLoaderRoute: typeof AdminVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventor/': {
      id: '/inventor/'
      path: '/'
      fullPath: '/inventor/'
      preLoaderRoute: typeof InventorIndexRouteImport
      parentRoute: typeof InventorRoute
    }
    '/inventor/finance': {
      id: '/inventor/finance'
      path: '/finance'
      fullPath: '/inventor/finance'
      preLoaderRoute: typeof InventorFinanceRouteImport
      parentRoute: typeof InventorRoute
    }
    '/inventor/history': {
      id: '/inventor/history'
      path: '/history'
      fullPath: '/inventor/history'
      preLoaderRoute: typeof InventorHistoryRouteImport
      parentRoute: typeof InventorRoute
    }
    '/inventor/ip-search': {
      id: '/inventor/ip-search'
      path: '/ip-search'
      fullPath: '/inventor/ip-search'
      preLoaderRoute: typeof InventorIpSearchRouteImport
      parentRoute: typeof InventorRoute
    }
    '/inventor/ledger': {
      id: '/inventor/ledger'
      path: '/ledger'
      fullPath: '/inventor/ledger'
      preLoaderRoute: typeof InventorLedgerRouteImport
      parentRoute: typeof InventorRoute
    }
    '/inventor/monitor': {
      id: '/inventor/monitor'
      path: '/monitor'
      fullPath: '/inventor/monitor'
      preLoaderRoute: typeof InventorMonitorRouteImport
      parentRoute: typeof InventorRoute
    }
    '/inventor/purchases': {
      id: '/inventor/purchases'
      path: '/purchases'
      fullPath: '/inventor/purchases'
      preLoaderRoute: typeof InventorPurchasesRouteImport
      parentRoute: typeof InventorRoute
    }
    '/inventor/recordings': {
      id: '/inventor/recordings'
      path: '/recordings'
      fullPath: '/inventor/recordings'
      preLoaderRoute: typeof InventorRecordingsRouteImport
      parentRoute: typeof InventorRoute
    }
    '/inventor/support': {
      id: '/inventor/support'
      path: '/support'
      fullPath: '/inventor/support'
      preLoaderRoute: typeof InventorSupportRouteImport
      parentRoute: typeof InventorRoute
    }
    '/inventor/tutorials': {
      id: '/inventor/tutorials'
      path: '/tutorials'
      fullPath: '/inventor/tutorials'
      preLoaderRoute: typeof InventorTutorialsRouteImport
      parentRoute: typeof InventorRoute
    }
    '/inventor/users': {
      id: '/inventor/users'
      path: '/users'
      fullPath: '/inventor/users'
      preLoaderRoute: typeof InventorUsersRouteImport
      parentRoute: typeof InventorRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/resolve-stream-token': {
      id: '/api/public/resolve-stream-token'
      path: '/api/public/resolve-stream-token'
      fullPath: '/api/public/resolve-stream-token'
      preLoaderRoute: typeof ApiPublicResolveStreamTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track-visit': {
      id: '/api/public/track-visit'
      path: '/api/public/track-visit'
      fullPath: '/api/public/track-visit'
      preLoaderRoute: typeof ApiPublicTrackVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/stream': {
      id: '/api/voice/stream'
      path: '/api/voice/stream'
      fullPath: '/api/voice/stream'
      preLoaderRoute: typeof ApiVoiceStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/api-v1/$': {
      id: '/api/public/api-v1/$'
      path: '/api/public/api-v1/$'
      fullPath: '/api/public/api-v1/$'
      preLoaderRoute: typeof ApiPublicApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppApiKeysRoute: typeof AppApiKeysRoute
  AppBillingRoute: typeof AppBillingRoute
  AppCreditsRoute: typeof AppCreditsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStreamRoute: typeof AppStreamRoute
  AppSupportRoute: typeof AppSupportRoute
  AppTutorialRoute: typeof AppTutorialRoute
  AppVoiceRoute: typeof AppVoiceRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApiKeysRoute: AppApiKeysRoute,
  AppBillingRoute: AppBillingRoute,
  AppCreditsRoute: AppCreditsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStreamRoute: AppStreamRoute,
  AppSupportRoute: AppSupportRoute,
  AppTutorialRoute: AppTutorialRoute,
  AppVoiceRoute: AppVoiceRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface InventorRouteChildren {
  InventorFinanceRoute: typeof InventorFinanceRoute
  InventorHistoryRoute: typeof InventorHistoryRoute
  InventorIpSearchRoute: typeof InventorIpSearchRoute
  InventorLedgerRoute: typeof InventorLedgerRoute
  InventorMonitorRoute: typeof InventorMonitorRoute
  InventorPurchasesRoute: typeof InventorPurchasesRoute
  InventorRecordingsRoute: typeof InventorRecordingsRoute
  InventorSupportRoute: typeof InventorSupportRoute
  InventorTutorialsRoute: typeof InventorTutorialsRoute
  InventorUsersRoute: typeof InventorUsersRoute
  InventorIndexRoute: typeof InventorIndexRoute
}

const InventorRouteChildren: InventorRouteChildren = {
  InventorFinanceRoute: InventorFinanceRoute,
  InventorHistoryRoute: InventorHistoryRoute,
  InventorIpSearchRoute: InventorIpSearchRoute,
  InventorLedgerRoute: InventorLedgerRoute,
  InventorMonitorRoute: InventorMonitorRoute,
  InventorPurchasesRoute: InventorPurchasesRoute,
  InventorRecordingsRoute: InventorRecordingsRoute,
  InventorSupportRoute: InventorSupportRoute,
  InventorTutorialsRoute: InventorTutorialsRoute,
  InventorUsersRoute: InventorUsersRoute,
  InventorIndexRoute: InventorIndexRoute,
}

const InventorRouteWithChildren = InventorRoute._addFileChildren(
  InventorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InventorRoute: InventorRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  OutputRoute: OutputRoute,
  PrivacyRoute: PrivacyRoute,
  RefundsRoute: RefundsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  TrustRoute: TrustRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AdminVoiceRoute: AdminVoiceRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicResolveStreamTokenRoute: ApiPublicResolveStreamTokenRoute,
  ApiPublicTrackVisitRoute: ApiPublicTrackVisitRoute,
  ApiVoiceStreamRoute: ApiVoiceStreamRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicApiV1SplatRoute: ApiPublicApiV1SplatRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
