// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const { data } = await supabase.auth.getSession()
    let session = data.session
    // getSession() returns the cached session without refreshing. Proactively
    // refresh when the access token has expired or is within 60s of expiring
    // so the server middleware doesn't reject with "JWT has expired".
    const nowSec = Math.floor(Date.now() / 1000)
    const expiresAt = session?.expires_at ?? 0
    const isStale = !session || expiresAt - nowSec < 60
    if (isStale) {
      const { data: refreshed, error } = await supabase.auth.refreshSession()
      if (!error && refreshed.session) {
        session = refreshed.session
      } else if (session && expiresAt <= nowSec) {
        // Refresh failed and the cached token is already expired — don't
        // send a known-expired bearer (server will 401). Drop the header.
        session = null
      }
    }
    const token = session?.access_token
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
