// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const { data } = await supabase.auth.getSession()
    let session = data.session
    // getSession() returns the cached session without refreshing. If the tab
    // was idle long enough for the access token to expire (or expire within
    // the next 30s), proactively refresh so the server middleware doesn't
    // reject the RPC with "JWT has expired".
    const nowSec = Math.floor(Date.now() / 1000)
    const expiresAt = session?.expires_at ?? 0
    if (session && expiresAt - nowSec < 30) {
      const { data: refreshed } = await supabase.auth.refreshSession()
      if (refreshed.session) session = refreshed.session
    }
    const token = session?.access_token
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
