// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const { data } = await supabase.auth.getSession()
    let session = data.session
    const nowSec = Math.floor(Date.now() / 1000)
    const expiresAt = session?.expires_at ?? 0
    // Refresh if we have a session that's expired or expiring within 60s.
    if (session && expiresAt - nowSec < 60) {
      const { data: refreshed, error } = await supabase.auth.refreshSession()
      if (!error && refreshed.session) {
        session = refreshed.session
      } else {
        // Refresh token is dead — clear local session and redirect to login
        // rather than calling the server with a known-expired bearer.
        await supabase.auth.signOut().catch(() => {})
        if (typeof window !== 'undefined' && !window.location.pathname.startsWith('/login')) {
          window.location.assign('/login')
        }
        throw new Error('Session expired. Please sign in again.')
      }
    }
    // Re-check freshness after potential refresh.
    const finalExp = session?.expires_at ?? 0
    if (!session || finalExp - Math.floor(Date.now() / 1000) <= 0) {
      if (typeof window !== 'undefined' && !window.location.pathname.startsWith('/login')) {
        window.location.assign('/login')
      }
      throw new Error('Not authenticated.')
    }
    return next({
      headers: { Authorization: `Bearer ${session.access_token}` },
    })
  },
)
